# SPDX-License-Identifier: 0BSD
extends SceneTree
const Extension=preload("res://addons/world_runtime/world_runtime.gdextension")
var failures:=0
func check(ok: bool,label: String) -> void:
	print(("PASS " if ok else "FAIL ")+label)
	if not ok: failures+=1
func _initialize() -> void: call_deferred("run")
func run() -> void:
	GDExtensionManager.load_extension("res://addons/world_runtime/world_runtime.gdextension")
	var store: RefCounted=ClassDB.instantiate("NativeEntityStore")
	check(store.configure(100004),"large mixed store configured")
	var stationary: PackedInt64Array=store.spawn_grid(100000,Vector3.ZERO,2,Vector3.ZERO)
	check(stationary.size()==100000 and store.statistics().moving==0,"100000 stationary entities stay outside moving set")
	var started:=Time.get_ticks_usec()
	for tick in 100: store.step(1.0/60)
	print("STATIC_100_TICKS_US ",Time.get_ticks_usec()-started)
	check(store.statistics().last_step_visited==0 and store.get_position(stationary[0])==Vector3.ZERO,"static ticks visit no entity slots and preserve position")
	var a: int=store.spawn(Vector3(1000,0,0),Vector3(10,0,0))
	var b: int=store.spawn(Vector3(1100,0,0),Vector3(20,0,0))
	var c: int=store.spawn(Vector3(1200,0,0),Vector3(30,0,0))
	store.step(0.1)
	check(store.statistics().last_step_visited==3 and store.get_position(c)==Vector3(1203,0,0),"tick visits three movers among 100003 entities")
	store.set_velocity(b,Vector3.ZERO);store.despawn(a);store.step(0.1)
	check(store.statistics().moving==1 and store.get_position(b)==Vector3(1102,0,0) and store.get_position(c)==Vector3(1206,0,0),"swap removal preserves remaining mover and sleeping position")
	var reused: int=store.spawn(Vector3(1300,0,0),Vector3.ZERO)
	check(reused>0 and not store.set_velocity(a,Vector3.ONE) and store.statistics().moving==1,"reused slot remains asleep and stale handle cannot wake it")
	store.set_velocity(b,Vector3(1,0,0));store.set_velocity(b,Vector3(1,0,0));store.step(0.1)
	check(store.statistics().moving==2 and is_equal_approx(store.get_position(b).x,1102.1),"repeated wake does not double integrate")
	var identity: int=store.persistent_id(c)
	var b_identity: int=store.persistent_id(b)
	var snapshot: PackedByteArray=store.capture_storage_snapshot()
	check(store.restore_storage_snapshot(snapshot) and store.statistics().moving==2,"snapshot restore rebuilds moving membership from velocity")
	c=store.resolve_identity(identity);store.step(0.1)
	check(is_equal_approx(store.get_position(c).x,1212.0),"restored mover continues integration")
	var found: Dictionary=store.query_sphere(Vector3.ZERO,0.1,8,1024)
	check(found.ok and found.complete and found.ids.size()==1,"sleeping entities remain in spatial queries")
	store.set_velocity(c,Vector3.ZERO)
	check(store.statistics().moving==1,"restored mover can sleep")
	store.despawn(store.resolve_identity(b_identity));store.step(0.1)
	check(store.statistics().moving==0 and store.statistics().last_step_visited==0,"removing last mover restores constant-work static tick")
	var overflow: RefCounted=ClassDB.instantiate("NativeEntityStore");overflow.configure(2)
	overflow.spawn(Vector3.ZERO,Vector3.ONE)
	overflow.spawn(Vector3(3.4e38,0,0),Vector3(3.4e38,0,0))
	var before: PackedByteArray=overflow.capture_storage_snapshot()
	check(not overflow.step(0.1) and overflow.capture_storage_snapshot()==before and overflow.statistics().ticks==0,"overflow rejects all moving entities before any position mutation")
	DirAccess.make_dir_recursive_absolute("res://reports")
	var report:=FileAccess.open("res://reports/entity_sleeping.json",FileAccess.WRITE)
	report.store_string(JSON.stringify({"failures":failures}));report.close()
	quit(1 if failures else 0)
