# SPDX-License-Identifier: 0BSD
extends SceneTree
var checks:=0
var failures:=0
func check(ok: bool,label: String) -> void:
	checks+=1
	if not ok: failures+=1
	print(("PASS " if ok else "FAIL ")+label)
func pose(x: float) -> PackedFloat32Array:
	return PackedFloat32Array([1,0,0,x,0,1,0,0,0,0,1,0])
func hash_of(bytes: PackedByteArray) -> PackedByteArray: return bytes.slice(bytes.size()-32)
func write(path: String,bytes: PackedByteArray) -> void:
	var file:=FileAccess.open(path,FileAccess.WRITE);file.store_buffer(bytes);file.close()
func cleanup(path: String) -> void:
	for name in DirAccess.get_directories_at(path): cleanup(path.path_join(name))
	for name in DirAccess.get_files_at(path): DirAccess.remove_absolute(path.path_join(name))
	DirAccess.remove_absolute(path)
func _initialize() -> void: call_deferred("run")
func run() -> void:
	GDExtensionManager.load_extension("res://addons/structures/structures.gdextension")
	var args:=OS.get_cmdline_user_args()
	if args.size()==4 and args[0]=="--reopen-model":
		var reopened=ClassDB.instantiate("NativeModelRegionStore")
		var ok: bool=reopened.open_store(args[1],"test/asset").ok
		if ok:
			var current: Dictionary=reopened.read_region(Vector3i.ZERO)
			var old: Dictionary=reopened.read_checkpoint_region(args[3].hex_decode(),Vector3i.ZERO)
			ok=current.ok and old.ok and hash_of(current.bytes).hex_encode()==args[2] and current.bytes!=old.bytes
		reopened.close();quit(0 if ok else 1);return
	var folder:=ProjectSettings.globalize_path("user://model_catalog_"+str(OS.get_process_id())+"_"+str(Time.get_ticks_usec()))
	DirAccess.make_dir_recursive_absolute(folder)
	var batch=ClassDB.instantiate("NativeStaticBatch");batch.configure_collision_only()
	batch.configure_asset("test/asset",BoxMesh.new())
	batch.upsert_instances(PackedInt64Array([1,2]),pose(1)+pose(-1))
	var original: PackedByteArray=batch.capture_region(Vector3i.ZERO)
	var negative: PackedByteArray=batch.capture_region(Vector3i(-1,0,0))
	var store=ClassDB.instantiate("NativeModelRegionStore")
	check(store.open_store(folder,"test/asset").ok,"new asset-bound model catalog opens")
	var rival=ClassDB.instantiate("NativeModelRegionStore")
	check(not rival.open_store(folder,"test/asset").ok,"second writer cannot acquire directory lease")
	check(store.publish_regions([original,negative],[PackedByteArray(),PackedByteArray()]).ok,"atomic publication admits two signed model regions")
	check(store.read_region(Vector3i.ZERO).bytes==original,"catalog reads exact checked model packet")
	var generation: int=store.stats().generation
	check(store.publish_region(original,hash_of(original)).ok and store.stats().generation==generation,"unchanged publication avoids generation churn")
	var pin: Dictionary=store.pin_checkpoint()
	check(pin.ok,"model catalog checkpoint pins old region versions")
	var checkpoint: PackedByteArray=pin.checkpoint
	batch.upsert_instances(PackedInt64Array([1]),pose(5))
	var newer: PackedByteArray=batch.capture_region(Vector3i.ZERO)
	check(not store.publish_region(newer,PackedByteArray()).ok,"stale expected checksum cannot overwrite committed region")
	check(store.publish_region(newer,hash_of(original)).ok,"matching expected checksum publishes new model version")
	check(store.read_checkpoint_region(checkpoint,Vector3i.ZERO).bytes==original,"checkpoint retains earlier packet after edit")
	var foreign=ClassDB.instantiate("NativeStaticBatch");foreign.configure_collision_only();foreign.configure_asset("test/other",BoxMesh.new())
	var wrong: PackedByteArray=foreign.capture_region(Vector3i(1,0,0))
	check(not store.publish_regions([negative,wrong],[hash_of(negative),PackedByteArray()]).ok and store.stats().regions==2,"mixed-asset batch rejects without partial publication")
	foreign.free()
	var block=ClassDB.instantiate("NativeBlockWorld")
	check(not store.publish_region(block.capture_region(Vector3i(3,0,0)),PackedByteArray()).ok,"model catalog rejects block packets")
	block.free()
	check(store.remove_region(Vector3i(-1,0,0),hash_of(negative)).ok,"conditional removal commits region deletion")
	var collected:=true
	for i in 10:
		var result: Dictionary=store.collect_garbage(1)
		collected=collected and result.ok and result.inspected<=1
	check(collected and store.read_checkpoint_region(checkpoint,Vector3i(-1,0,0)).bytes==negative,"bounded collection preserves checkpoint-only region")
	store.close()
	var child_output: Array=[]
	var child:=OS.execute(OS.get_executable_path(),["--headless","--path",ProjectSettings.globalize_path("res://"),"--script","res://tests/model_region_store.gd","--","--reopen-model",folder,hash_of(newer).hex_encode(),checkpoint.hex_encode()],child_output,true)
	check(child==0,"separate engine process reopens current and checkpoint model versions")
	check(not rival.open_store(folder,"test/other").ok,"reopening under another asset identity fails")
	var blocks=ClassDB.instantiate("NativeBlockRegionStore")
	check(not blocks.open_store(folder).ok,"block catalog reader rejects model catalog format")
	check(store.open_store(folder,"test/asset").ok and store.read_region(Vector3i.ZERO).bytes==newer,"disk reopen restores committed model version")
	check(store.read_checkpoint_region(checkpoint,Vector3i.ZERO).bytes==original,"checkpoint retention survives disk reopen")
	check(store.activate_checkpoint(checkpoint).ok and store.read_region(Vector3i(-1,0,0)).bytes==negative,"checkpoint activation restores deleted region")
	check(batch.unload_region(newer),"live collection unloads its captured version")
	check(not batch.restore_region(store.read_region(Vector3i.ZERO).bytes),"older checkpoint cannot overwrite live unloaded version")
	check(store.publish_region(newer,hash_of(original)).ok and batch.restore_region(store.read_region(Vector3i.ZERO).bytes),"committed matching packet restores live unloaded records")
	var blob:=folder.path_join("blobs").path_join(hash_of(newer).hex_encode()+".tfrg")
	write(blob,PackedByteArray([1,2,3]))
	check(not store.read_region(Vector3i.ZERO).ok,"corrupt immutable blob is detected on read")
	check(not store.publish_region(newer,hash_of(newer)).ok,"publication refuses to overwrite corrupted immutable data")
	write(blob,newer)
	store.close()
	write(folder.path_join("catalog.tfrc"),PackedByteArray([1,2,3]))
	check(not store.open_store(folder,"test/asset").ok,"corrupt primary catalog requires explicit recovery")
	check(store.open_store(folder,"test/asset",true).ok and store.read_region(Vector3i.ZERO).bytes==original,"explicit backup recovery reads prior committed catalog")
	check(store.publish_region(newer,hash_of(original)).ok,"recovered catalog can publish a new commit")
	check(store.release_checkpoint(checkpoint).ok,"checkpoint release is explicit")
	store.close();batch.free()
	cleanup(folder)
	check_snapshot_storage(folder+"_snapshot")
	check_partial_storage(folder+"_partial")
	await check_worker(folder+"_worker")
	DirAccess.make_dir_recursive_absolute("res://reports")
	var report:=FileAccess.open("res://reports/model_region_store.json",FileAccess.WRITE)
	report.store_string(JSON.stringify({"checks":checks,"failures":failures}));report.close()
	print("MODEL_REGION_STORE checks=",checks," failures=",failures)
	quit(1 if failures else 0)
func check_snapshot_storage(folder: String) -> void:
	DirAccess.make_dir_recursive_absolute(folder)
	var batch=ClassDB.instantiate("NativeStaticBatch");batch.configure_collision_only();batch.configure_asset("test/full",BoxMesh.new())
	var store=ClassDB.instantiate("NativeModelRegionStore")
	check(store.open_store(folder,"test/full").ok,"full-snapshot store opens")
	var ids:=PackedInt64Array();ids.resize(100000)
	var transforms:=PackedFloat32Array();transforms.resize(1200000)
	for i in 100000:
		ids[i]=i+1
		var value:=pose((int(i/1000)-50)*32+(i%10))
		for j in 12: transforms[i*12+j]=value[j]
	check(batch.upsert_instances(ids,transforms),"full snapshot fixture has 100000 unique IDs in 100 regions")
	var original: PackedByteArray=batch.capture_snapshot()
	check(store.publish_snapshot(original).ok and store.stats().regions==100,"whole model snapshot publishes all regions in one catalog commit")
	var generation: int=store.stats().generation
	check(store.publish_snapshot(original).ok and store.stats().generation==generation,"unchanged full publication preserves generation")
	var pin: Dictionary=store.pin_checkpoint()
	check(pin.ok and store.read_checkpoint(pin.checkpoint).snapshot==original,"full checkpoint reconstruction is byte exact at 100000 placements")
	store.close()
	check(store.open_store(folder,"test/full").ok and store.read_checkpoint(pin.checkpoint).snapshot==original,"full checkpoint reconstructs after disk reopen")
	for region in range(-50,49): batch.unload_region(batch.capture_region(Vector3i(region,0,0)))
	batch.upsert_instances(PackedInt64Array([100000]),pose(49*32+10))
	var partial: Dictionary=batch.capture_storage_state()
	check(batch.region_stats().resident_instances==1000 and publish_partial(store,partial).ok,"100000-instance partial save commits with only 1000 transforms resident")
	var partial_pin: Dictionary=store.pin_checkpoint()
	var restored=ClassDB.instantiate("NativeStaticBatch");restored.configure_collision_only();restored.configure_asset("test/full",BoxMesh.new())
	restored.restore_snapshot(original);restored.upsert_instances(PackedInt64Array([100000]),pose(49*32+10))
	check(partial_pin.ok and store.read_checkpoint(partial_pin.checkpoint).snapshot==restored.capture_snapshot(),"large partial save preserves 99000 unloaded records and exact resident edit")
	restored.free();batch.restore_snapshot(original)
	batch.set_instances(BoxMesh.new(),pose(64))
	var reduced: PackedByteArray=batch.capture_snapshot()
	check(store.publish_snapshot(reduced).ok and store.stats().regions==1,"authoritative full save removes demolished regions")
	check(store.read_checkpoint(pin.checkpoint).snapshot==original,"demolition does not alter pinned full snapshot")
	var packet: PackedByteArray=batch.capture_region(Vector3i(2,0,0))
	check(batch.unload_region(packet) and not store.publish_snapshot(batch.capture_snapshot()).ok and store.stats().regions==1,"partial collection cannot publish a truncated full save")
	batch.restore_region(packet)
	var corrupted:=reduced.duplicate();corrupted[0]^=1
	check(not store.publish_snapshot(corrupted).ok and store.stats().regions==1,"malformed full snapshot preserves committed state")
	# The packet API permits independently valid regions; complete reconstruction
	# must reject cross-region ID collisions instead of dropping one silently.
	batch.upsert_instances(PackedInt64Array([1]),pose(96))
	var duplicate: PackedByteArray=batch.capture_region(Vector3i(3,0,0))
	check(store.publish_region(duplicate,PackedByteArray()).ok,"fixture publishes individually valid packet with cross-region duplicate ID")
	var bad_pin: Dictionary=store.pin_checkpoint()
	check(bad_pin.ok and not store.read_checkpoint(bad_pin.checkpoint).ok,"complete reconstruction rejects duplicate IDs across regions")
	batch.set_instances(BoxMesh.new(),PackedFloat32Array())
	var empty: PackedByteArray=batch.capture_snapshot()
	check(store.publish_snapshot(empty).ok and store.stats().regions==0,"empty full save commits total model demolition")
	var empty_pin: Dictionary=store.pin_checkpoint()
	check(empty_pin.ok and store.read_checkpoint(empty_pin.checkpoint).snapshot==empty,"empty checkpoint reconstructs valid asset-bound empty snapshot")
	check(not store.read_checkpoint(PackedByteArray([1])).ok,"full checkpoint read validates identity length")
	store.close();batch.free();cleanup(folder)
func publish_partial(store: RefCounted,state: Dictionary,checkpoint:=PackedByteArray()) -> Dictionary:
	return store.publish_storage_state(state.resident,state.unavailable_keys,state.unavailable_checksums,checkpoint)
func check_partial_storage(folder: String) -> void:
	DirAccess.make_dir_recursive_absolute(folder)
	var batch=ClassDB.instantiate("NativeStaticBatch");batch.configure_collision_only();batch.configure_asset("test/partial",BoxMesh.new())
	batch.upsert_instances(PackedInt64Array([1,2,3]),pose(-1)+pose(1)+pose(64))
	var original: PackedByteArray=batch.capture_snapshot()
	var store=ClassDB.instantiate("NativeModelRegionStore");store.open_store(folder,"test/partial")
	store.publish_snapshot(original)
	var old_pin: Dictionary=store.pin_checkpoint()
	var packet: PackedByteArray=batch.capture_region(Vector3i(-1,0,0))
	batch.unload_region(packet);batch.upsert_instances(PackedInt64Array([2]),pose(5));batch.remove_instances(PackedInt64Array([3]))
	var state: Dictionary=batch.capture_storage_state()
	check(state.unavailable_keys==PackedInt32Array([-1,0,0]) and state.unavailable_checksums==hash_of(packet),"partial capture includes exact sorted unavailable references")
	check(batch.capture_snapshot().is_empty(),"partial storage capture does not weaken whole-save guard")
	check(publish_partial(store,state).ok and store.stats().regions==2,"partial save preserves unloaded region and removes resident demolition")
	var pin: Dictionary=store.pin_checkpoint()
	var reference=ClassDB.instantiate("NativeStaticBatch");reference.configure_collision_only();reference.configure_asset("test/partial",BoxMesh.new())
	reference.restore_snapshot(original);reference.upsert_instances(PackedInt64Array([2]),pose(5));reference.remove_instances(PackedInt64Array([3]))
	check(store.read_checkpoint(pin.checkpoint).snapshot==reference.capture_snapshot(),"partial save reconstructs exact edited logical collection")
	check(store.read_checkpoint(old_pin.checkpoint).snapshot==original,"partial save preserves older pinned world")
	var generation: int=store.stats().generation
	check(publish_partial(store,state).ok and store.stats().generation==generation,"unchanged partial save avoids generation churn")
	var malformed: Dictionary=state.duplicate();malformed.unavailable_keys=PackedInt32Array([-1,0])
	check(not publish_partial(store,malformed).ok,"partial save rejects malformed manifest lengths")
	malformed=state.duplicate();malformed.unavailable_keys=PackedInt32Array([-1,0,0,-1,0,0]);malformed.unavailable_checksums=hash_of(packet)+hash_of(packet)
	check(not publish_partial(store,malformed).ok,"partial save rejects duplicate region references")
	malformed=state.duplicate();malformed.unavailable_keys=PackedInt32Array([0,0,0])
	check(not publish_partial(store,malformed).ok,"partial save rejects resident/unavailable overlap")
	malformed=state.duplicate();malformed.unavailable_checksums=PackedByteArray();malformed.unavailable_checksums.resize(32)
	check(not publish_partial(store,malformed).ok and store.stats().generation==generation,"stale references fail without changing catalog")
	var forged=ClassDB.instantiate("NativeStaticBatch");forged.configure_collision_only();forged.configure_asset("test/partial",BoxMesh.new())
	forged.upsert_instances(PackedInt64Array([1]),pose(32))
	malformed=state.duplicate();malformed.resident=forged.capture_snapshot()
	check(not publish_partial(store,malformed).ok,"partial save rejects resident ID colliding with unloaded ID")
	forged.free()
	reference.upsert_instances(PackedInt64Array([1]),pose(-5))
	var newer: PackedByteArray=reference.capture_region(Vector3i(-1,0,0))
	store.publish_region(newer,hash_of(packet))
	check(not publish_partial(store,state).ok,"advanced active catalog cannot silently substitute unloaded version")
	check(publish_partial(store,state,pin.checkpoint).ok,"explicit pinned checkpoint supplies exact older unloaded version")
	check(not publish_partial(store,state,PackedByteArray([1])).ok,"partial save validates checkpoint identity length")
	store.close()
	check(store.open_store(folder,"test/partial").ok and store.read_checkpoint(pin.checkpoint).snapshot!=PackedByteArray(),"partial save and checkpoint survive disk reopen")
	check(batch.restore_region(store.read_region(Vector3i(-1,0,0)).bytes) and batch.capture_snapshot()==store.read_checkpoint(pin.checkpoint).snapshot,"live unloaded region restores from partial-save catalog without losing resident edits")
	var full: Dictionary=batch.capture_storage_state()
	check(full.unavailable_keys.is_empty() and publish_partial(store,full).ok,"fully resident capture uses the same storage API")
	var blob:=folder.path_join("blobs").path_join(hash_of(packet).hex_encode()+".tfrg")
	batch.unload_region(packet);state=batch.capture_storage_state();write(blob,PackedByteArray([7]))
	check(not publish_partial(store,state).ok,"partial save detects corrupt unavailable blob before publication")
	write(blob,packet)
	store.close();batch.free();reference.free();cleanup(folder)
func wait_results(queue: RefCounted,count: int) -> Array:
	var results: Array=[]
	var deadline:=Time.get_ticks_msec()+10000
	while results.size()<count and Time.get_ticks_msec()<deadline:
		results.append_array(queue.poll(count-results.size()))
		if results.size()<count: await process_frame
	return results
func check_worker(folder: String) -> void:
	DirAccess.make_dir_recursive_absolute(folder)
	var batch=ClassDB.instantiate("NativeStaticBatch");batch.configure_collision_only();batch.configure_asset("test/io",BoxMesh.new())
	batch.upsert_instances(PackedInt64Array([1,2]),pose(1)+pose(64))
	var original: PackedByteArray=batch.capture_snapshot()
	var queue=ClassDB.instantiate("NativeModelRegionIO")
	check(queue.start(folder,"",2,12000000)==0,"model worker rejects empty asset identity synchronously")
	var opening: int=queue.start(folder,"test/io",2,12000000)
	var results: Array=await wait_results(queue,1)
	check(opening>0 and results.size()==1 and results[0].ok and results[0].ticket==opening,"model worker opens store with ticketed completion")
	var rival=ClassDB.instantiate("NativeModelRegionStore")
	check(not rival.open_store(folder,"test/io").ok,"background worker exclusively owns disk store")
	var state: Dictionary=batch.capture_storage_state()
	var save: int=queue.publish_storage_state(state.resident,state.unavailable_keys,state.unavailable_checksums)
	var pin: int=queue.pin_checkpoint()
	check(save>0 and pin>save and queue.list_regions()==0,"request cap includes accepted work and unread completions")
	state.resident[0]=0;state.unavailable_keys.append(999)
	results=await wait_results(queue,2)
	check(results.size()==2 and results[0].ok and results[0].ticket==save and results[1].ok and results[1].ticket==pin,"worker owns immutable input and executes save before checkpoint")
	if results.size()!=2 or not results[1].ok:
		queue.join();queue.poll(64);batch.free();cleanup(folder);return
	var checkpoint: PackedByteArray=results[1].checkpoint
	var read: int=queue.read_checkpoint(checkpoint)
	results=await wait_results(queue,1)
	check(read>0 and results.size()==1 and results[0].ok and results[0].snapshot==original,"background full checkpoint reconstructs exact saved collection")
	var packet: PackedByteArray=batch.capture_region(Vector3i.ZERO)
	batch.unload_region(packet);batch.upsert_instances(PackedInt64Array([2]),pose(70));state=batch.capture_storage_state()
	save=queue.publish_storage_state(state.resident,state.unavailable_keys,state.unavailable_checksums,checkpoint)
	pin=queue.pin_checkpoint();queue.request_stop()
	check(queue.read_region(Vector3i.ZERO)==0,"stop rejects new requests")
	queue.join();results=queue.poll(64)
	check(results.size()==2 and results[0].ticket==save and results[0].ok and results[1].ticket==pin and results[1].ok,"shutdown drains accepted partial save and checkpoint in FIFO order")
	check(not queue.stats().running and queue.stats().outstanding==0 and queue.stats().reserved_bytes==0,"poll releases all completion payload reservations after shutdown")
	check(queue.start(folder,"test/io",8,6000000)>pin,"restart preserves monotonically increasing tickets")
	results=await wait_results(queue,1)
	check(results.size()==1 and results[0].ok,"restarted worker reopens saved catalog")
	read=queue.read_region(Vector3i.ZERO)
	check(read>0 and queue.read_region(Vector3i(2,0,0))==0,"byte cap reserves worst-case model packet across pending and unread work")
	queue.join()
	check(queue.stats().outstanding==1 and queue.stats().reserved_bytes==5600232,"unread completion retains reservation even after worker exit")
	check(queue.start(folder,"test/io",8,6000000)==0,"restart cannot discard unread results")
	results=queue.poll(1)
	check(results.size()==1 and results[0].ok and results[0].bytes==packet,"bounded read returns exact unloaded region packet")
	check(queue.stats().high_bytes<=6000000 and queue.stats().high_requests<=8,"observed reservations stay within configured budgets")
	check(queue.start(folder,"bad asset",2,6000000)>0,"invalid nonempty asset receives asynchronous open result")
	queue.join();results=queue.poll(1)
	check(results.size()==1 and not results[0].ok and not queue.stats().running,"failed worker open terminates cleanly and returns failure")
	check(rival.open_store(folder,"test/io").ok,"worker shutdown and failed reopen release directory lease")
	rival.close();batch.free();cleanup(folder)
