# SPDX-License-Identifier: 0BSD
extends SceneTree
const Library=preload("res://addons/structures/prefab_library.gd")
var failures:=0
func check(ok: bool,label: String) -> void:
	print(("PASS " if ok else "FAIL ")+label)
	if not ok: failures+=1
func _initialize() -> void:
	GDExtensionManager.load_extension("res://addons/structures/structures.gdextension")
	var blocks=ClassDB.instantiate("NativeBlockWorld")
	var library=Library.new()
	library.directory="user://tests/prefab_library_%d" % Time.get_ticks_usec()
	library.load_library()
	check(library.assets.is_empty(),"missing library starts empty")
	check(not library.capture(blocks,"Test").ok,"capture requires two corners")
	var word:=3+(1<<3)+(1<<5)
	blocks.set_cells(PackedInt32Array([10,20,30,1,11,21,30,word]))
	library.select_corner(true,Vector3i(11,21,30));library.select_corner(false,Vector3i(10,20,30))
	var before: PackedByteArray=blocks.capture_snapshot()
	var result: Dictionary=library.capture(blocks,"Wood stairs module")
	check(result.ok and result.asset.get_cell_count()==2,"reversed corners capture occupied cells")
	check(blocks.capture_snapshot()==before,"capture does not mutate source world")
	var reopened=Library.new();reopened.directory=library.directory;reopened.load_library()
	check(reopened.assets.size()==1 and reopened.assets[0].get_records()==result.asset.get_records() and reopened.assets[0].resource_name=="Wood stairs module","saved native prefab reopens with exact cells and title")
	check(blocks.place_prefab(reopened.assets[0],Vector3i(40,20,30),1),"reopened prefab can be placed with rotation")
	check(blocks.get_cell(Vector3i(40,20,30))==9 and blocks.get_cell(Vector3i(40,21,31))==3+(2<<3)+(1<<5),"placement preserves material and composes rotation")
	check(not library.capture(blocks," ").ok,"empty name rejected")
	library.select_corner(false,Vector3i(1000,1000,1000))
	check(not library.selection_within_limit(),"oversized selection reports capture limit before saving")
	check(not library.capture(blocks,"Oversize").ok and library.assets.size()==1,"oversized selection rejected without saving")
	library.select_corner(true,Vector3i(90,90,90));library.select_corner(false,Vector3i(91,91,91))
	check(not library.capture(blocks,"Empty").ok,"empty selection rejected")
	var source: String=result.path
	var bytes:=FileAccess.get_file_as_bytes(source)
	var world_before: PackedByteArray=blocks.capture_snapshot()
	var archived: Dictionary=library.archive(result.asset)
	check(archived.ok and not FileAccess.file_exists(source) and FileAccess.get_file_as_bytes(archived.path)==bytes and library.assets.is_empty(),"archive moves exact asset bytes out of active library")
	check(blocks.capture_snapshot()==world_before,"archiving prefab preserves placed buildings")
	check(not library.archive(result.asset).ok,"already archived asset cannot be archived again")
	reopened.load_library()
	check(reopened.assets.is_empty(),"new library instance excludes archive")
	var restored: Dictionary=reopened.restore_latest()
	check(restored.ok and restored.asset.get_records()==result.asset.get_records() and FileAccess.get_file_as_bytes(restored.path)==bytes,"restore after reopen recovers exact prefab")
	check(not reopened.restore_latest().ok,"empty archive restore is harmless")
	var builtin: Resource=load("res://addons/structures/prefabs/stair_flight.tres")
	check(not reopened.archive(builtin).ok,"built-in prefab cannot be archived")
	var stacked: Dictionary=reopened.stack(builtin,3,"Stacked stairs")
	check(stacked.ok and stacked.asset.get_cell_count()==builtin.get_cell_count()*3,"library stacks module through native composition")
	check(not reopened.stack(builtin,1,"Invalid").ok and not reopened.stack(builtin,33,"Invalid").ok and not reopened.stack(null,4,"Invalid").ok,"library validates repeat count and source")
	reopened.load_library()
	check(reopened.assets.size()==2 and reopened.assets.any(func(asset: Resource): return asset.resource_name=="Stacked stairs" and asset.get_records()==stacked.asset.get_records()),"stacked asset survives library reopen")
	var frontage: Dictionary=reopened.frontage(builtin,3,8,2,1703,"Street modules")
	check(frontage.ok and frontage.asset.get_cell_count()==builtin.get_cell_count()*6,"frontage saves through personal prefab library")
	check(not reopened.frontage(builtin,2,7,2,1703,"Invalid").ok and not reopened.frontage(null,2,8,2,1703,"Invalid").ok,"invalid frontage saves no asset")
	reopened.load_library()
	check(reopened.assets.size()==3 and reopened.assets.any(func(asset: Resource): return asset.resource_name=="Street modules" and asset.get_records()==frontage.asset.get_records() and asset.get_meta("street_width")==8),"frontage geometry and layout metadata survive reopen")
	for file: String in DirAccess.get_files_at(library.directory): DirAccess.remove_absolute(library.directory.path_join(file))
	DirAccess.remove_absolute(library.directory.path_join("archive"))
	DirAccess.remove_absolute(library.directory)
	blocks.free()
	quit(1 if failures else 0)
