# SPDX-License-Identifier: 0BSD
extends SceneTree
var checks:=0
var failures:=0
func check(ok: bool,label: String) -> void:
	checks+=1
	if not ok: failures+=1
	print(("PASS " if ok else "FAIL ")+label)
func _initialize() -> void: call_deferred("run")
func run() -> void:
	GDExtensionManager.load_extension("res://addons/player_runtime/player_runtime.gdextension")
	var inbox=ClassDB.instantiate("NativeRewardInbox")
	var inventory=ClassDB.instantiate("NativePlayerInventory")
	inventory.register_item(101,1);inventory.register_item(102,1);inventory.grant(101,32,0)
	check(inbox.accept(PackedInt64Array([101,3,102,5,101,2]),8).ok,"receipt accumulates duplicate material rows")
	check(inbox.get_pending()==PackedInt64Array([101,5,102,5]),"pending counts are exact")
	var before: PackedByteArray=inbox.capture_storage_snapshot()
	for receipt in [-1,0,7,8]: check(not inbox.accept(PackedInt64Array([101,1]),receipt).ok and inbox.capture_storage_snapshot()==before,"old or duplicate receipt cannot repeat a reward")
	var stock: Dictionary=inventory.snapshot()
	check(not inbox.claim(inventory,PackedInt64Array([101,1]),stock.revision).ok and inbox.capture_storage_snapshot()==before and inventory.snapshot()==stock,"full inventory retains reward with no mutation")
	inventory.consume(0,1,stock.revision)
	stock=inventory.snapshot()
	check(not inbox.claim(inventory,PackedInt64Array([101,1,102,1]),stock.revision).ok and inbox.capture_storage_snapshot()==before and inventory.snapshot()==stock,"late claim capacity failure changes neither participant")
	check(inbox.claim(inventory,PackedInt64Array([102,1]),stock.revision).ok and inbox.get_pending()==PackedInt64Array([101,5,102,4]),"partial claim transfers exact requested quantity")
	before=inbox.capture_storage_snapshot();stock=inventory.snapshot()
	check(not inbox.claim(inventory,PackedInt64Array([101,1]),stock.revision-1).ok and inbox.capture_storage_snapshot()==before,"stale claim leaves pending rewards intact")
	check(not inbox.claim(inventory,PackedInt64Array([101,3,101,3]),stock.revision).ok and inbox.capture_storage_snapshot()==before,"duplicate claim rows cannot overdraw pending stock")
	check(not inbox.accept(PackedInt64Array([101,1,102,-1]),9).ok and inbox.capture_storage_snapshot()==before,"invalid receipt tail cannot partly accrue or advance receipt")
	check(inbox.accept(PackedInt64Array([101,1]),9).ok,"failed receipt can be corrected without losing its identity")
	before=inbox.capture_storage_snapshot()
	check(before.size()==400 and inbox.validate_snapshot(before),"fixed bounded format validates")
	for offset in [0,4,8,16,20,388,392]:
		var bad:=before.duplicate();bad.encode_u32(offset,0xffffffff)
		if offset==8: bad.encode_u32(12,0xffffffff)
		if offset in [20,392]: bad.encode_u32(offset+4,0xffffffff)
		check(not inbox.restore_storage_snapshot(bad) and inbox.capture_storage_snapshot()==before,"malformed snapshot rejects atomically at %d"%offset)
	check(not inbox.validate_snapshot(before.slice(0,399)),"truncated save rejected")
	var long:=before.duplicate();long.append(0);check(not inbox.validate_snapshot(long),"trailing data rejected")
	var path:="user://reward_inbox_%d.bin"%OS.get_process_id()
	var file:=FileAccess.open(path,FileAccess.WRITE);file.store_buffer(before);file.close()
	file=FileAccess.open(path,FileAccess.READ);var disk:=file.get_buffer(file.get_length());file.close()
	var restored=ClassDB.instantiate("NativeRewardInbox")
	check(restored.restore_storage_snapshot(disk) and restored.get_pending()==inbox.get_pending() and restored.get_last_receipt()==9,"disk roundtrip preserves pending stock and receipt watermark")
	check(not restored.accept(PackedInt64Array([101,1]),9).ok,"reload does not allow replaying last receipt")
	GDExtensionManager.load_extension("res://addons/world_runtime/world_runtime.gdextension")
	GDExtensionManager.load_extension("res://addons/volumetric_terrain/terrain_core.gdextension")
	var core=ClassDB.instantiate("TerrainCore")
	var codec=preload("res://addons/volumetric_terrain/mesh_codec.gd")
	var terrain_reply: PackedByteArray=core.execute(codec.command(4))
	var archive=ClassDB.instantiate("NativeWorldArchive")
	var sections: Dictionary={"terrain":terrain_reply.slice(12),"player_loadout":inventory.capture_storage_snapshot(),"pending_rewards":inbox.capture_storage_snapshot()}
	var packed: PackedByteArray=archive.encode(sections)
	file=FileAccess.open(path,FileAccess.WRITE);file.store_buffer(packed);file.close()
	var decoded: Dictionary=archive.decode(archive.read(ProjectSettings.globalize_path(path)))
	check(decoded.ok and decoded.sections==sections,"compound disk archive preserves terrain, inventory and pending rewards as one snapshot")
	var loaded_inventory=ClassDB.instantiate("NativePlayerInventory")
	loaded_inventory.register_item(101,1);loaded_inventory.register_item(102,1)
	check(loaded_inventory.restore_storage_snapshot(decoded.sections.player_loadout) and restored.restore_storage_snapshot(decoded.sections.pending_rewards) and loaded_inventory.capture_storage_snapshot()==inventory.capture_storage_snapshot() and restored.get_pending()==inbox.get_pending(),"claimed inventory and unclaimed remainder restore together")
	DirAccess.remove_absolute(path)
	var bounded=ClassDB.instantiate("NativeRewardInbox")
	check(bounded.accept(PackedInt64Array([101,1000000000000]),1).ok,"maximum per-item pending balance admitted")
	before=bounded.capture_storage_snapshot()
	check(not bounded.accept(PackedInt64Array([102,1,101,1]),2).ok and bounded.capture_storage_snapshot()==before,"balance overflow cannot partly accrue another item")
	bounded=ClassDB.instantiate("NativeRewardInbox")
	var entries:=PackedInt64Array()
	for item in range(1,33): entries.append_array(PackedInt64Array([item,1]))
	check(bounded.accept(entries,1).ok,"exact distinct-item capacity admitted")
	before=bounded.capture_storage_snapshot()
	check(not bounded.accept(PackedInt64Array([1,1,33,1]),2).ok and bounded.capture_storage_snapshot()==before,"distinct-item overflow preserves prior balances and receipt")
	print("REWARD_INBOX ",JSON.stringify({"checks":checks,"failures":failures}))
	quit(1 if failures else 0)
